<h1>Capstone Project Notebook: Battle of the Neighbourhoods</h1>

In [1]:
import pandas as pd
import numpy as np
print ('Hello Capstone Project Course!')

Hello Capstone Project Course!

<h2>Week 3 - Segmenting and Clustering Neighborhoods in Toronto: Question 1</h2>

In [2]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]
df.rename(columns={'Postal Code': 'PostalCode'}, inplace=True)
df = df[df.Borough != 'Not assigned']
df['Neighbourhood'].loc[df['Neighbourhood'] == 'Not assigned'] =  df.Borough
df.reset_index(drop=True, inplace=True)
df

,PostalCode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [3]:
df.shape

(103, 3)

<h2>Week 3 - Segmenting and Clustering Neighborhoods in Toronto: Question 2</h2>

<h3> Unable to load geocoder package - Using Geospatial data provided instead from : http://cocl.us/Geospatial_data </h3>

In [12]:
gspdf = pd.read_csv('http://cocl.us/Geospatial_data')
gspdf.rename(columns={'Postal Code': 'PostalCode'}, inplace=True)
gspdf.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [17]:
df_merged = pd.merge(gspdf, df, on='PostalCode')
df_merged.rename(columns={'Latitude_x': 'Latitude'}, inplace=True)
df_merged.drop(columns='Latitude_y', inplace=True)
df_merged.head()

,PostalCode,Latitude,Longitude,Borough,Neighbourhood
0,M1B,43.806686,-79.194353,Scarborough,"Malvern, Rouge"
1,M1C,43.784535,-79.160497,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,43.763573,-79.188711,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,43.770992,-79.216917,Scarborough,Woburn
4,M1H,43.773136,-79.239476,Scarborough,Cedarbrae

In [20]:
tor_df = df_merged[['PostalCode','Borough','Neighbourhood','Latitude','Longitude']]
tor_df.head()

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476